all: stats figs
	rsync -av stats/* ~/Papers/cognitive-tutors/PNAS\ article/stats/
	rsync -av figs/* ~/Papers/cognitive-tutors/PNAS\ article/figures/ --exclude "*.png"
# 	cp -R stats/* ~/Papers/cognitive-tutors/PNAS\ article/stats/
# 	cp -R figs/* ~/Papers/cognitive-tutors/PNAS\ article/figures/